rule:
  - require_japanese_comment:
      label: comment_rule
      format:
        custom:
          lines:
            - "#"
          blocks:
            - start: "\"\"\""
              end: "\"\"\""
      message: コメントを日本語にしてください
