rule:
  - label: no-system-exit
    type: forbidden_texts
    keywords:
      - System.exit
    message: Do not use System.exit
    match:
      - pattern: file_ends_with
        keywords: [.java]
        cond: or

guideline:
  - message: Check exception handling
