# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-hoge/rec_lint/refs/tags/v0.0.5/schema/rec_lint.schema.json

rule:
  - forbidden_texts:
      label: var_dump の禁止
      texts: [ var_dump ]
      message: デバッグ残りは削除し、必要な出力は Logger を使うこと

  - require_php_doc:
      label: public class の PHPDoc は必須
      option:
        class: public
      message: PHPDoc を記述すること
