rule:
  - label: comment_rule
    type: require_japanese_comment
    format:
      custom:
        lines:
          - "#"
        blocks:
          - start: "\"\"\""
            end: "\"\"\""
    message: コメントを日本語にしてください
