rule:
  - label: no-println
    type: forbidden_texts
    keywords:
      - System.out.println
    message: Use logger instead
    match:
      - pattern: file_ends_with
        keywords: [.java]
        cond: or

guideline:
  - message: Check logging configuration
