rule:
  - label: comment_rule
    type: require_english_comment
    format:
      custom:
        lines: ["#"]
        blocks:
          - start: '"""'
            end: '"""'
    message: コメントを英語にしてください
