rule:
  - require_english_comment:
      label: comment_rule
      format:
        custom:
          lines: ["#"]
          blocks:
            - start: '"""'
              end: '"""'
      message: コメントを英語にしてください
