rule:
  - forbidden_texts:
      label: todo_check
      texts: [TODO]
      message: TODO禁止
  - forbidden_patterns:
      label: fixme_pattern
      patterns: ["FIXME:.*"]
      message: FIXMEパターン禁止
  - require_japanese_comment:
      label: japanese_comment
      format:
        lang: java
      message: コメントを日本語にしてください
      match:
        - pattern: file_ends_with
          keywords: [.kt, .java]
          cond: or
