rule:
  - label: kotest_test_all_public
    type: require_kotest_test
    option:
      test_directory: src/test/kotlin
      require: all_public
      test_file_suffix: Test
    message: テストファイルが必要です
