rule:
  - forbidden_patterns:
      label: 最初のパターン
      patterns:
        - NOTEXIST
      message: パターン違反1
  - forbidden_patterns:
      label: 次のパターン
      patterns:
        - FIXME
      message: パターン違反2
