rule:
  - label: 最初のパターン
    type: forbidden_patterns
    patterns:
      - NOTEXIST
    message: パターン違反1
  - label: 次のパターン
    type: forbidden_patterns
    patterns:
      - FIXME
    message: パターン違反2
